### ISSUE TITLE
Cannot set > 1 cookies

### ISSUE THREAD

**Issue by murdercode** [edgurgel/httpoison#106]
When I try to set 2 or more cookies I give only the first one

case HTTPoison.get("https://httpbin.org/cookies", %{}, hackney: [cookie: [{"cookie1", "1"} , {"cookie2", "2"}]]) do			
			{:ok, %HTTPoison.Response{status_code: 200, body: body}} ->
				IO.puts body
			{_, %HTTPoison.Response{status_code: _, body: _}} ->
				# Nothing to do
				end
end

(Sorry for eventually mistakes, i cleanup a complex code for write here) :)

**Comment by murdercode** [comment]
Solved

case HTTPoison.get("https://httpbin.org/cookies", %{}, hackney: [cookie: "cookie1=1 cookie=2"]) do

**Comment by edgurgel** [comment]
I wonder if we should support the first instead of the one that is working..

**Comment by aphillipo** [comment]
Yes, I was looking at the test_case and it passes an array to cookie with a tuple in it... This isn't working for me!

I will try the second way...

**Comment by murdercode** [comment]
I tried to set domain and path but without success. The only way for me was to integrate a recall in phantomjs/casperjs, that's not a clean solution but it works.

With the second way I got my script working: https://i.imgur.com/bYu0Xvb.png

**Comment by nscyclone** [comment]
Not sure whether someone is still interested in this but it looks like I finally could set several cookies and specify their domain, path and other options. Here is a working example:
```elixir
iex(1)> HTTPoison.get("https://httpbin.org/headers", %{}, hackney: [cookie: [{"foo", "0", [{:path, "/headers"}, {:domain, ".httpbin.org"}, {:secure, true}, {:max_age, 300}]}, {"bar", "1", [{:path, "/"}, {:domain, ".httpbin.org"}]}]])
{:ok,
 %HTTPoison.Response{body: "{\n  \"headers\": {\n    \"Cookie\": \"foo=0; Version=1; Expires=Sat, 14-May-2016 14:05:33 GMT; Max-Age=300; Domain=.httpbin.org; Path=/headers; Secure, bar=1; Version=1; Domain=.httpbin.org; Path=/\", \n    \"Host\": \"httpbin.org\", \n    \"User-Agent\": \"hackney/1.6.0\"\n  }\n}\n",
  headers: [{"Server", "nginx"}, {"Date", "Sat, 14 May 2016 14:00:32 GMT"},
   {"Content-Type", "application/json"}, {"Content-Length", "263"},
   {"Connection", "keep-alive"}, {"Access-Control-Allow-Origin", "*"},
   {"Access-Control-Allow-Credentials", "true"}], status_code: 200}}
```
In my opinion, it would be fine to update `README` or [the cookies test](https://github.com/edgurgel/httpoison/blob/master/test/httpoison_test.exs#L108) to make this more clear. What do you think about this, @edgurgel?

**Comment by edgurgel** [comment]
That would be amazing! Could you send a PR updating both? 🎉

**Comment by nscyclone** [comment]
I've just started playing around with different tests and now it looks like I hurried with the conclusions. It turned out that the above example is not working in HTTParrot and this is the expected behaviour. Actually I was mislead a little by one of the previous comments and the [hackney docs](https://github.com/benoitc/hackney/blob/master/doc/ha..): several cookie attributes are described there but according to the [latest RFC](https://tools.ietf.org/rfc/rfc6265.txt) the client must not send anything but a list of `key=value` separated by a semicolon and a space in the `Cookie` header. These attributes should be used by server inside the `Set-Cookie` headers instead and this was mentioned in an [appropriate issue](https://github.com/benoitc/hackney/issues/194).
So, the correct working way to pass multiple cookies is the following (both HTTParrot and httpbin give the identical expected result):
```elixir
iex(1)> HTTPoison.get!("http://httparrot.herokuapp.com/cookies", %{}, hackney: [cookie: ["foo=1; bar=2"]])
%HTTPoison.Response{
 body: "{\n  \"cookies\": {\n    \"foo\": \"1\",\n    \"bar\": \"2\"\n  }\n}",
 headers: [{"Connection", "keep-alive"}, ...], 
 status_code: 200
}

iex(2)> HTTPoison.get!("https://httpbin.org/cookies", %{}, hackney: [cookie: ["foo=1; bar=2"]])
%HTTPoison.Response{
 body: "{\n  \"cookies\": {\n    \"bar\": \"2\", \n    \"foo\": \"1\"\n  }\n}\n",
 headers: [{"Server", "nginx"}, ...], 
 status_code: 200
}
```
Finally, I updated the `README` and the cookies test to make this easy to find and use: #135.

**Comment by edgurgel** [comment]
Thanks for the detailed info 👍
