### ISSUE TITLE
Can we get a nicer error for :badarg?

### ISSUE THREAD

**Issue by sikanhe** [edgurgel/httpoison#196]
I have an app that encountered hackney throwring :badarg error on numerous occasions (malformatted url).  Since it throws, it forces me to use try/catch as control flow instead of the nice
ok/error tuples. 

Is it possible to just catch it in HTTPoison and have it return {:error, :badarg} ? Maybe we should make the error nicer in this case as well, Like {:error, "Invalid Url"}

**Comment by edgurgel** [comment]
Hm.. I would probably try to change hackney to provide a better error... Similar issue: https://github.com/edgurgel/httpoison/pull/141

**Comment by sikanhe** [comment]
I am sorry, I was actually using an older version of HTTPoison that threw the error instead of using :error turple, it looks like from that pull request it has been fixed ! Apologies.

**Comment by joshprice** [comment]
I ran into this when I was missing an environment variable which set the base URL of an external API. The result was a `:badarg` error which was almost impossible to track down/debug. Mainly because it didn't give any hints that it was the URL arg that was missing.

Agree that changing this in Hackney is the best way forward. Doesn't look like there are any existing issues relating to this. https://github.com/benoitc/hackney/issues?utf8=%E2%9C%93&q=is%3Aissue%20badarg%20

**Comment by joshprice** [comment]
@edgurgel since you've done a bunch more and are more familiar with Hackney than I, is there any chance you could give me hand raising an issue or crafting a PR for this?

**Comment by joshprice** [comment]
Thinking about it some more, is there any reason why HTTPoison couldn't pre-validate certain args before passing on to Hackney?

**Comment by edgurgel** [comment]
Well we can check if the url is "valid" somehow and error out before we even send to hackney. That would work 👍

**Comment by aung-ko** [comment]
@edgurgel is that working in current version now? The checking url before sending to hackney thing.
