### ISSUE TITLE
Allow process_* callbacks to fail the request

### ISSUE THREAD

**Issue by jasonwebster** [edgurgel/httpoison#57]
When wrapping `HTTPoison.Base` to create an opinionated API client, it would be nice to be able to return an `{:error, reason}` tuple if the response body (or headers) was not what we expected. The current implementation of `response/3` (https://github.com/edgurgel/httpoison/blob/master/lib/httpoison/base.ex#L211) prevents that from being possible.

**Comment by jasonwebster** [comment]
In retrospect, I suppose this can be accomplished by pattern matching `body` and `headers` in the `Response` struct.

**Comment by edgurgel** [comment]
That's a really interesting use case and I have good news!

I'm working on a similar library that can achieve more than this. My idea is that you can "stop" or "error" the request even before the request is being done. For example if the body is not a json and the client expects a JSON or the url is not valid or the headers are incorrect. 

It will give way more control to the user. It should be pushed [here](https://github.com/edgurgel/httpehaviour) in the next days. 

It will have the same features HTTPoison has, but with a different way of handling the pre-post process callbacks.

**Comment by edgurgel** [comment]
I just released [HTTPehaviour](https://github.com/edgurgel/httpehaviour).

**Comment by pmontrasio** [comment]
Sorry to add to a closed issue, but my team just run into this. We'd like to wrap `HTTPoison.Base` in our API but we have to handle errors from the server before returning a response to our clients. Our process_response_body fails decoding JSON because we get a 500 response with an empty body. 
I considered switching to HTTPBeaviour for a couple of minutes, then I noticed that the last commit is from 2015.
Is there any change to add the callback stopping functionalities to HTTPoison? That would solve our problem.

**Comment by edgurgel** [comment]
Hey @pmontrasio, 

I think the options are:

* Use `process_response` which receives the whole response struct at once;
* Override `request/5` and call `super`;
