### ISSUE TITLE
Unclear on how to follow redirects when wrapping HTTPoison.Base

### ISSUE THREAD

**Issue by ptrckbrwn** [edgurgel/httpoison#59]
I've been banging my head on this for a while, is it possible?

I'll make a PR with some docs on how to do it in the README once I know how, as I'm sure other people are wondering the same.

Thanks!

**Comment by edgurgel** [comment]
Oh hey! Yeah we should probably support a direct option instead of passing this through the hackney keyword. Here's an example on how to do it:

https://github.com/edgurgel/httpoison/blob/master/test/httpoison_test.exs#L67-L75

**Comment by fairbairn** [comment]
Can't quite tell how to get the location value back after the redirect.  Is it possible to access the hackney.location value from the response object returned after it get request has occurred with hackney value of [ follow_redirect: true ] ?

**Comment by edgurgel** [comment]
Hi @fairbairn, I think what you are looking for is being discussed here: https://github.com/edgurgel/httpoison/issues/90#issuecomment-153897977

**Comment by sgnl** [comment]
here's a reference to following redirects in tests: https://github.com/edgurgel/httpoison/blob/3481d567adcb06d129dfec3c69aa87d1719f7a8b/test/httpoison_test.exs#L89-L103

the previous link by @edgurgel uses `master` so the link is outdated. The one I have here uses a blob commit hash instead of branch name
